# -------------------------------
# Site Settings
# -------------------------------
include:
  - _pages
locale: "en-US"
site_theme: "default"

title: "Dr. Zahreddine Bouslama"
title_separator: "-"
name: "Dr. Zahreddine Bouslama"

description: "Behavioural Real Estate Finance (Europe) — housing markets • behavioural biases • econometrics • reproducible analytics (Python)"

url: "https://zahreddinebouslama.github.io"
baseurl: ""

repository: "ZahreddineBouslama/zahreddinebouslama.github.io"

markdown: kramdown
highlighter: rouge
permalink: /:categories/:title/

# -------------------------------
# Author (Sidebar Profile)
# -------------------------------

author:
  avatar: "profile.jpg"   # place your image in /images/
  name: "Dr. Zahreddine Bouslama"
  bio: "Behavioural Real Estate Finance (Europe)"
  location: "Luxembourg / Europe"
  employer:
  uri:
  email:
  github: "ZahreddineBouslama"
  linkedin: "zahreddine-b-29192214"
  orcid: "0000-0002-2904-5654"
  googlescholar:
  twitter:

# -------------------------------
# Plugins
# -------------------------------

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-include-cache

# -------------------------------
# Defaults
# -------------------------------

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true

# -------------------------------
# Exclude
# -------------------------------

exclude:
  - node_modules
  - vendor
